volumes:
  fluent-bit-config:
  loki-data:
  grafana-data:

services:

  nodejs-app:
    build:
      context: ./app

    container_name: nodejs-app

    ports:
      - "3000:3000"
    
    volumes:
      - ./app:/app


  config-generator:
    image: docker:cli

    container_name: fluent-bit-config-generator

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - fluent-bit-config:/generated

    depends_on:
      nodejs-app:
        condition: service_started

    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for nodejs-app..."

        until docker inspect nodejs-app >/dev/null 2>&1; do
          sleep 1
        done

        CONTAINER_ID=$$(docker inspect -f '{{.Id}}' nodejs-app)

        echo "======================================"
        echo "nodejs-app container found"
        echo "Container ID: $$CONTAINER_ID"
        echo "======================================"

        printf '%s\n' \
          '[SERVICE]' \
          '    Flush           1' \
          '    Log_Level       info' \
          '    Parsers_File    /fluent-bit/etc/parsers.conf' \
          '' \
          '[INPUT]' \
          '    Name              tail' \
          "    Path              /var/lib/docker/containers/$$CONTAINER_ID/*-json.log" \
          '    Tag               nodejs-app' \
          '    Parser            docker' \
          '    Refresh_Interval  5' \
          '    Mem_Buf_Limit     10MB' \
          '    Skip_Long_Lines   On' \
          '' \
          '[FILTER]' \
          '    Name          parser' \
          '    Match         nodejs-app' \
          '    Key_Name      log' \
          '    Parser        app_json' \
          '    Reserve_Data  On' \
          '' \
          '[FILTER]' \
          '    Name          modify' \
          '    Match         nodejs-app' \
          '    Copy          request   request_lbl' \
          '    Copy          method  method_lbl' \
          '    Copy          status  status_lbl' \
          '' \
          '[OUTPUT]' \
          '    Name              loki' \
          '    Match             nodejs-app' \
          '    Host              loki' \
          '    Port              3100' \
          '    Labels            job=fluent-bit,service=nodejs-app' \
          '    Label_Keys        $$level_lbl,$$method_lbl,$$status_lbl,$$request_lbl' \
          > /generated/fluent-bit.conf

        echo ""
        echo "Generated Fluent Bit configuration:"
        echo "======================================"
        cat /generated/fluent-bit.conf
        echo ""
        echo "Configuration generation completed."

  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - nodejs-app


  fluent-bit:
    image: fluent/fluent-bit:5.1

    container_name: fluent-bit

    volumes:
      - fluent-bit-config:/fluent-bit/etc/generated
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    
    command:
      - /fluent-bit/bin/fluent-bit
      - -c
      - /fluent-bit/etc/generated/fluent-bit.conf

    depends_on:
      config-generator:
        condition: service_completed_successfully
      
      loki:
        condition: service_started
  
  loki:
    image: grafana/loki:latest

    container_name: loki

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/local-config.yaml

    volumes:
      - ./loki:/loki


  grafana:
    image: grafana/grafana:latest

    container_name: grafana

    ports:
      - "3001:3000"

    volumes:
      - ./grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
      - loki