apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-09-10T05:11:34Z"
  labels:
    app: nodejs-app
  name: nodejs-app-service
  namespace: default
  resourceVersion: "16382"
  uid: c15efe35-c2c9-40fa-9e04-bc741f7df920
spec:
  clusterIP: 10.96.229.202
  clusterIPs:
  - 10.96.229.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}